# Generated by Django 4.0.6 on 2022-08-04 11:38

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsimage',
            name='small',
            field=models.BooleanField(default=False, verbose_name='Уменьшенный размер иконки'),
        ),
        migrations.AlterField(
            model_name='description',
            name='heading_2_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_descr_photo, verbose_name='Картинка колонки 1'),
        ),
        migrations.AlterField(
            model_name='description',
            name='heading_2_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_descr_photo, verbose_name='Картинка колонки 2'),
        ),
        migrations.AlterField(
            model_name='description',
            name='heading_2_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_descr_photo, verbose_name='Картинка колонки 3'),
        ),
    ]
