# Generated by Django 4.0.6 on 2022-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rewardsimage_small_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основная характеристика (цветная)'),
        ),
    ]
