# Generated by Django 4.0.6 on 2022-08-08 11:54

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_specification_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_icons, verbose_name='Картинка'),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
