# Generated by Django 4.0.6 on 2022-08-17 11:58

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Заголовок слайдера')),
                ('description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('desktop_image', models.ImageField(upload_to=product.models.upload_slider_image, verbose_name='Картинка для компьютерной версии сайта')),
                ('mobile_image', models.ImageField(upload_to=product.models.upload_slider_image, verbose_name='Картинка для мобильной версии сайта')),
                ('url_to', models.URLField(verbose_name='Ссылка на страницу')),
            ],
        ),
    ]
