# Generated by Django 4.0.6 on 2022-08-25 08:59

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_variety_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок колонки')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание колонки')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_descr_photo, verbose_name='Картинка колонки')),
            ],
        ),
        migrations.RenameField(
            model_name='description',
            old_name='heading_3_title',
            new_name='color_section_title',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_1',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_1_text',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_1_title',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_2',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_2_text',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_2_title',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_3',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_3_text',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_2_image_3_title',
        ),
        migrations.AddField(
            model_name='description',
            name='features',
            field=models.ManyToManyField(help_text='Желательно не больше 3 на 1 модель', to='product.feature', verbose_name='Спец. возмодности'),
        ),
    ]
