# Generated by Django 4.0.6 on 2022-08-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='heading_4_video_1',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_4_video_2',
        ),
        migrations.RemoveField(
            model_name='description',
            name='heading_4_video_3',
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_4_video_1', models.URLField(blank=True, null=True, verbose_name='Видео №1')),
                ('descr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_urls', to='product.description')),
            ],
        ),
    ]
