# Generated by Django 4.0.6 on 2022-08-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_description_heading_4_video_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='heading_3_subtitle',
            new_name='color_section_subtitle',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='heading_1_text',
            new_name='reward_title',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='heading_4_title',
            new_name='video_section_title',
        ),
        migrations.AlterField(
            model_name='videourl',
            name='heading_4_video_1',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
