# Generated by Django 4.0.6 on 2022-09-23 18:28

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_heading_3_subtitle_description_color_section_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='desktop_image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='mobile_image',
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(default='Текст кнопки', max_length=30, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', upload_to=product.models.upload_slider_image, verbose_name='Картинка слайдера'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default='Заголовок слайдера', max_length=100, verbose_name='Заголовок слайдера'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое описание слайдера'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_to',
            field=models.URLField(default='/', verbose_name='Ссылка на страницу'),
        ),
    ]
