# Generated by Django 4.0.6 on 2022-10-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_slider_desktop_image_remove_slider_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный слайд'),
        ),
    ]
